result_dict = {
    # "urls_found": [],
    # "urls_not_found": [],
    # "urls_response": [],
    # "sql": [],
    # "xss": [],
    # "spider": [],
    # "html_injection": [],
    # # "dorks": [],
    # "list_dorks": [],
    # "sub": [],
    # "ip_reverse": [],
    # "scan_ports": "",
    # "hash_en": [],
    # "hash_identifier": [],
    # "users_by_wordpress": [],
    # "message": "",
}
